config/routes.rb
Rails.application.routes.draw do

  root 'site/home#index'

  namespace :site do
    get 'home', to: 'home#index'
    resources :accounts, except: [:show]
    resources :categories, except: [:show]
    resources :expenses, except: [:show]
    resources :expense_types, except: [:show]
    resources :incomes, except: [:show]
    resources :income_types, except: [:show]
    resources :transactions, except: [:show]
    resources :members,  except: [:show, :destroy]
  end

  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    get 'dashboard', to: 'dashboard#index'
    resources :admins, except: [:show]
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members

end

app/controllers/site/accounts_controller.rb
class Site::AccountsController < SiteController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.where(member: current_member)
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)
    @account.member = current_member

    respond_to do |format|
      if @account.save
        format.html { redirect_to site_accounts_path, notice: "A Conta (#{@account.description}) foi salva com sucesso!" }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to site_accounts_path, notice: "A Conta (#{@account.description}) foi atualizada com sucesso!" }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to site_accounts_path, notice: "A Conta (#{@account.description}) foi excluída com sucesso!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:description, :amount, :member_id)
    end
end

app/controllers/site/categories_controller.rb
/class Site::CategoriesController < SiteController
	before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.where(member: current_member)
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.member = current_member

    respond_to do |format|
      if @category.save
        format.html { redirect_to redirect_route, notice: "A Categoria (#{@category.description}) foi salva com sucesso!" }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    #redirect_route = @category.kind_transaction == 1 ? site_expense_types_path : site_income_types_path
    
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to redirect_route, notice: "A Categoria (#{@category.description}) foi atualizada com sucesso!" }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    categoria = @category.description
    @category.destroy
    respond_to do |format|
      format.html { redirect_to site_categories_path, notice: "A Categoria (#{categoria}) foi deletada com sucesso!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:kind_transaction, :member_id, :description)
    end
end
/

app/controllers/site/expense_type_controller.rb
class Site::ExpenseTypeController < SiteController
  before_action :set_expense_type, only: [:edit, :update, :destroy]

  def index
    @expense_types = Category.where(kind_transaction: 1, member: current_member)
  end

  def new
    @expense_type = Category.new
  end

  def edit
  end

  def create
    @expense_type = Category.new(expense_type_params)
    @expense_type.member = current_member
    @expense_type.kind_transaction = 1

    respond_to do |format|
      if @expense_type.save
        format.html { redirect_to site_expense_type_index_path, notice: "A Categoria (#{@expense_type.description}) foi salva com sucesso!" }
        format.json { render :show, status: :created, location: @expense_type }
      else
        format.html { render :new }
        format.json { render json: @expense_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @expense_type.update(expense_type_params)
        format.html { redirect_to site_expense_type_index_path, notice: "A Categoria (#{@expense_type.description}) foi atualizada com sucesso!" }
        format.json { render :show, status: :ok, location: @expense_type }
      else
        format.html { render :edit }
        format.json { render json: @expense_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    tipoDespesa = @expense_type.description
    @expense_type.destroy
    respond_to do |format|
      format.html { redirect_to site_expense_type_index_path, notice: "A Categoria (#{tipoDespesa}) foi deletada com sucesso!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense_type
      @expense_type = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_type_params
      params.require(:expense_type).permit(:kind_transaction, :member_id, :description)
    end
end

app/controllers/site/expense_types_controller.rb
class Site::ExpenseTypesController < SiteController #Site::CategoriesController 
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.where(kind_transaction: 1, member: current_member)
    @categories_type = 1
  end

  def new
    @category = Category.new
    @anddress = site_expense_types_path
  end

  def edit
    @anddress = site_expense_type_path
  end

  def create
    @category = Category.new(category_params)
    @category.member = current_member
    @category.kind_transaction = 1

    respond_to do |format|
      if @category.save
        format.html { redirect_to site_expense_types_path, notice: "A Categoria (#{@category.description}) foi salva com sucesso!" }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to site_expense_types_path, notice: "A Categoria (#{@category.description}) foi atualizada com sucesso!" }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    tipoDespesa = @category.description
    @category.destroy
    respond_to do |format|
      format.html { redirect_to site_expense_types_path, notice: "A Categoria (#{tipoDespesa}) foi deletada com sucesso!" }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:kind_transaction, :member_id, :description)
  end
  
end

app/controllers/site/expenses_controller.rb
class Site::ExpensesController < SiteController#Site::TransactionsController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  def index
    @transactions = Transaction.where(kind_transaction: 1, member_id: current_member).order('date DESC')
    @transaction_type = 1
  end

  def new
    @transaction = Transaction.new
    @anddress = site_expenses_path
    @transaction_type = 1
  end

  def edit
    @anddress = site_expense_path
    @transaction_type = 1
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.member = current_member
    @transaction.kind_transaction = 1

    if @transaction.paid == true
      debit
    end

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to site_expenses_path, notice: "A Transação (#{@transaction.description}) foi salva com sucesso!" }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @transaction_save = Transaction.find(@transaction.id) #Busca no BD a Transação Existente e guarda os valores
    @account_save = Account.find(@transaction_save.account_id) #Busca a conta inicial da transação existente

    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to site_expenses_path, notice: "A Transação (#{@transaction.description}) foi atualizada com sucesso!" }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
    
    if (@transaction_save.account_id) == (@transaction.account_id) #Verifica se atualização ocorre na mesma conta cadastrada
      if (@transaction_save.paid == false) && (@transaction.paid == true)
        debit
      elsif (@transaction_save.paid == true) && (@transaction.paid == false)
        credit
        elsif (@transaction_save.paid == true) && (@transaction.paid == true)
        update_debit 
      end
    else #Aqui as contas são diferentes
      if (@transaction_save.paid == false) && (@transaction.paid == true)
        change_account
      elsif (@transaction_save.paid == true) && (@transaction.paid == false)
        credit
      elsif (@transaction_save.paid == true) && (@transaction.paid == true)
        debit
        credit
      end
    end
  end

  def destroy
    transacao = @transaction.description
    @transaction_save = Transaction.find(@transaction.id) #Busca no BD a Transação Existente e guarda os valores
    @account_save = Account.find(@transaction_save.account_id) #Busca a conta inicial da transação existente
    
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to site_expenses_path, notice: "A Transação (#{transacao}) foi deletada com sucesso!" }
      format.json { head :no_content }
    end

    if @transaction.paid == true
      credit
    end
  end

  private

    def debit #Debita valor de uma nova transação paid=true ou debita de uma conta que se iniciou com paid=false  
      @account_actual = Account.find(@transaction.account_id) 
      @account_actual.update(amount: @account_actual.amount - @transaction.amount)
    end

    def credit #Devolve valor pago para a conta debitada
      @account_save.update(amount: @account_save.amount + @transaction.amount)
    end

    def change_account #Transação não paga em uma conta que se torna paga em outra
      @new_account = Account.find(@transaction.account_id)
      @new_account.update(amount: @new_account.amount - @transaction.amount)
    end

    def update_debit
      if @transaction_save.amount > @transaction.amount
        @account_save.update(amount: @account_save.amount + (@transaction_save.amount - @transaction.amount))
      else
        @account_save.update(amount: @account_save.amount - (@transaction.amount - @transaction_save.amount))
      end
    end

    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    def transaction_params
      params.require(:transaction).permit(:member_id, :kind_transaction, :description, :amount, :date, :category_id, :account_id, :paid)
    end
end

app/controllers/site/home_controller.rb
class Site::HomeController < SiteController 
  def index
  end
end

app/controllers/site/income_types_controller.rb
class Site::IncomeTypesController < SiteController#Site::CategoriesController 
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.where(kind_transaction: 2, member: current_member)
    @categories_type = 2
  end

  def new
    @category = Category.new
    @anddress = site_income_types_path
  end

  def edit
    @anddress = site_income_type_path
  end

  def create
    @category = Category.new(category_params)
    @category.member = current_member
    @category.kind_transaction = 2

    respond_to do |format|
      if @category.save
        format.html { redirect_to site_income_types_path, notice: "A Categoria (#{@category.description}) foi salva com sucesso!" }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to site_income_types_path, notice: "A Categoria (#{@category.description}) foi atualizada com sucesso!" }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    tipoReceita = @category.description
    @category.destroy
    respond_to do |format|
      format.html { redirect_to site_income_types_path, notice: "A Categoria (#{tipoReceita}) foi deletada com sucesso!" }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:kind_transaction, :member_id, :description)
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_action :authenticate_member!
  layout "site"
end

app/helpers/site/accounts_helper.rb
module Site::AccountsHelper
end

app/helpers/site/categories_helper.rb
module Site::CategoriesHelper
end

app/helpers/site/expense_types_helper.rb
module Site::ExpenseTypesHelper
end

app/helpers/site/expenses_helper.rb
module Site::ExpensesHelper

  def category_options
  	@kind = @transaction_type
    @Kind_category = Category.where(kind_transaction: @kind, member_id: current_member)
  end
  
	def account_options
    @accountUser = Account.where(member_id: current_member)
  end
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
  def sald_to_account
    @sald = Account.where(member: current_member).sum("amount_cents")
  end

  def total_incomes
    @sald = Transaction.where(member: current_member, kind_transaction: 2).sum("amount_cents")
  end

  def total_expenses
    @sald = Transaction.where(member: current_member, kind_transaction: 1).sum("amount_cents")
  end
end

app/helpers/site/income_types_helper.rb
module Site::IncomeTypesHelper
end

app/helpers/site/incomes_helper.rb
module Site::IncomesHelper

  def category_options
    @kind = @transaction_type
    @Kind_category = Category.where(kind_transaction: @kind, member_id: current_member)
  end

	def account_options
    @accountUser = Account.where(member_id: current_member)
  end

  def sum_income
  	@sum_icomes = Transaction.where(member_id: current_member, kind_transaction: 2).sum("amount_cents")
  end
end

app/helpers/site/members_helper.rb
module Site::MembersHelper
end

app/helpers/site/transactions_helper.rb
module Site::TransactionsHelper
end

app/views/site/transactions_shared/_form.html.erb
<h1 class="page-header"></h1>
  <% if @transaction.errors.any? %><!-- Verifica se há erros e joga o erro na tela - SM -->
  <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <ul><!-- Envia as mensagens de erro para a tela - SM -->
        <% @transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  </div>
  <% end %>
<div class="panel panel-default">
  <div class="panel-heading">
    <%= action %><!-- Recebe o nome da página -->
  </div>
  <div class="panel-body">
    <div class="col-lg-6">
      <%# Verifica se a tranação é uma despesa ou receita %>
       <%= form_for [:site, @transaction], url: @anddress do |f| %> 
        <%#= f.hidden_field :member_id, @member %>
        <div class="form-group">
          <%= f.label :date %><br>
          <%= f.date_field :date %>
        </div>

        <div class="form-group">
          <%= f.label :description %><br>
          <%= f.text_field :description, class: "form-control", placeholder: "Ex: Comida" %>
        </div>

        <div class="form-group">
          <%= f.label :category_id %><br>
          <%= collection_select(:transaction, :category_id, category_options, :id, :description, class:"form-control") %>
        </div>

        <div class="form-group">
          <%= f.label :account_id %><br>
          <%= collection_select(:transaction, :account_id, account_options, :id, :description) %>
        </div>

        <div class="form-group input-group">
            <span class="input-group-addon">R$</span>
            <%= f.text_field :amount, class: "form-control" %>
        </div>

        <div class="checkbox">
            <%= f.label :paid %><br>
            <%= f.check_box :paid %>
        </div>

        <button type="submit" class="btn btn-default">Salvar</button>
      <% end %><!-- Fim-Formulario -->
    </div>
    <div class="table-responsive">
    </div><!-- /.table-responsive -->
  </div><!-- /.panel-body -->
</div>

app/views/site/transactions_shared/_index.html.erb
<h1 class="page-header"></h1>
<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h5><b><%= action %></b></h5><!-- Recebe o nome da página -->
      <%# Verifica qual o botão "new" será liberado a partir do tipo de transação %>
      <% if @transaction_type == 1 %>
        <%= link_to new_site_expense_path, class: "btn btn-success pull-right", style: "margin-top: -30px" do %>
          <i class="fa fa-plus"></i>
        <% end %>
      <% elsif @transaction_type == 2%>
        <%= link_to new_site_income_path, class: "btn btn-success pull-right", style: "margin-top: -30px" do %>
          <i class="fa fa-plus"></i>
        <% end %>
      <% end %>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Status</th>
              <th>Data</th>
              <th>Descrição</th>
              <% if  @transaction_type == 0 %>
                <td><b>Transação</b></td>
              <% end %>
              <th>Categoria</th>
              <th>Conta</th>
              <th>Valor</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @transactions.each do |transaction| %>
            <tr>
              <td>
                <% if transaction.paid == true %>
                  <button type="button" class="btn btn-success btn-circle">
                    <i class="fa"></i>
                  </button>
                <% else %>
                  <button type="button" class="btn btn-danger btn-circle">
                    <i class="fa"></i>
                  </button>
                <% end %>
              </td>
                <td><%= transaction.date %></td>
                <td><%= transaction.description %></td>
                <% if  @transaction_type == 0 %>
                  <td><%= transaction.kind_transaction_br %></td>
                <% end %>
                <td><%= transaction.category.description %></td>
                <td><%= transaction.account.description %></td>
                <td><%= humanized_money_with_symbol(transaction.amount) %></td>
                <td>
                <%# Verifica qual os botões "edit/destroy" serão liberados a partir do tipo de transação %>
                <% if @transaction_type == 1 %>
                  <%= link_to edit_site_expense_path(transaction), class: "btn btn-primary btn-circle" do %>
                    <i class="fa fa-edit"></i>
                  <% end %>
                  <%= link_to site_expense_path(transaction.id), method: :delete, class: "btn btn-danger btn-circle", 
                    data: {confirm: "Você deseja realmente excluir (#{transaction.description})?"} do %>
                    <i class="fa fa-minus"></i>
                  <% end %>
                <% elsif @transaction_type == 2 %>
                  <%= link_to edit_site_income_path(transaction), class: "btn btn-primary btn-circle" do %>
                    <i class="fa fa-edit"></i>
                  <% end %>
                  <%= link_to site_income_path(transaction.id), method: :delete, class: "btn btn-danger btn-circle", 
                    data: {confirm: "Você deseja realmente excluir (#{transaction.description})?"} do %>
                    <i class="fa fa-minus"></i>
                  <% end %>
                <% end %>
                <%# Fim verificação de botões %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <!-- /.table-responsive -->
    </div>
    <!-- /.panel-body -->
  </div>
  <!-- /.panel -->
</div>