config/routes.rb
Rails.application.routes.draw do

  root 'site/home#index'

  namespace :site do
    get 'home', to: 'home#index'
    resources :accounts, except: [:show]
    resources :categories, except: [:show]
    resources :expenses, except: [:show]
    resources :expense_types, except: [:show]
    resources :incomes, except: [:show]
    resources :income_types, except: [:show]
    resources :transactions, except: [:show]
    resources :members,  except: [:show, :destroy]
  end

  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    get 'dashboard', to: 'dashboard#index'
    resources :admins, except: [:show]
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members

end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]

  def index
    @admins = Admin.all
  end

  def new
    @admin = Admin.new
  end

  def edit
  end

  def create
    @admin = Admin.new(admins_params)
    if @admin.save
      redirect_to backoffice_admins_path, notice: "O Administrador (#{@admin.email}) foi salvo com sucesso!"  
    else
      render :new
    end
  end

  def update
    pwd = params[:admin][:password]
    pwd_confirm = params[:admin][:password_confirmation]

    if pwd.blank? && pwd_confirm.blank?
      params[:admin].delete(:password)
      params[:admin].delete(:password_confirmation)
    end

    if @admin.update(admins_params)
      redirect_to backoffice_admins_path, notice: "O Administrador (#{@admin.email}) foi atualizado com sucesso!"
    else
	    render :edit
    end
  end

  def destroy
    admin_email = @admin.email
    if @admin.destroy
      redirect_to backoffice_admins_path, notice: "O Administrador (#{admin_email}) foi excluído com sucesso!"
    else
      rende :index
    end
  end

  private
    def set_admin
      @admin = Admin.find(params[:id])
    end

    def admins_params
      params.require(:admin).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController
  def index
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout "backoffice"
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/views/backoffice/admins/edit.html.erb
<%= render partial: "backoffice/admins/shared/form", 
					 locals: {action: "Editando Administrador"} %>

app/views/backoffice/admins/index.html.erb
<h1 class="page-header">Administradores</h1>
  <div class="panel panel-default">
    <div class="panel-heading">
      Listando Adiministradores
      <%= link_to new_backoffice_admin_path, class: "btn btn-success pull-right", style: "margin-top: -6px" do %>
        <i class="fa fa-plus"></i>
      <% end %>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th>Id</th>
              <th>Nome</th>
              <th>Email</th>
              <th>Tipo de Acesso</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @admins.each do |admin| %>
            <tr>
              <td><%= admin.id %></td>
              <td><%= admin.name %></td>
              <td><%= admin.email %></td>
              <td><%= admin.role_br %></td>
              <td>
                <%= link_to edit_backoffice_admin_path(admin), class: "btn btn-primary btn-circle" do %>
                  <i class="fa fa-edit"></i>
                <% end %>

                <% if current_admin.id != admin.id %>
                  <%= link_to backoffice_admin_path(admin), method: :delete, class: "btn btn-danger btn-circle",
                    data: {confirm: "Você deseja realmente excluir <b>#{admin.email}</b>?"} do %>
                    <i class="fa fa-minus"></i>
                  <% end %>
                <% else %>
                  <%= link_to '#', disabled: "disabled", class: "btn btn-danger btn-circle" do %>
                    <i class="fa fa-minus"></i>
                  <% end %>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div><!-- /.table-responsive -->
    </div><!-- /.panel-body -->
  </div>

app/views/backoffice/admins/new.html.erb
<%= render partial: "backoffice/admins/shared/form", 
					 locals: {action: "Criando um novo Administrador"} %>